name: Java 11 Gradle Build

on:
  push:
    branches: [master]

########################## STAGING BUILD AND DEPLOY ##########################
jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Add SHORT_SHA env property with commit short sha
      #  run: curl -I https://ktn-jenkins01p.eagro.az:59943/multibranch-webhook-trigger/invoke?token=azizanimalmulti
        run: curl -I https://youtube.com
